/*
 * OptionsContainer.java
 *
 * Created on September 20, 2007, 4:23 PM
 */

package samp.options;

/**
 *
 * @author  ludo
 */
public class OptionsContainer extends javax.swing.JFrame {
    
    /** Creates new form OptionsContainer */
    public OptionsContainer() {
        initComponents();
        tabsPanel.addTab("General", new GeneralPanel());
        tabsPanel.addTab("Apache 2", new Apache2Panel());
        tabsPanel.addTab("PHP", new PHPPanel());
        tabsPanel.addTab("MySQL", new MySQLPanel());
        tabsPanel.addTab("FTP", new FTPPanel());
        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        tabsPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("samp/tray/Bundle"); // NOI18N
        titleLabel.setText(bundle.getString("LABEL_Title")); // NOI18N
        getContentPane().add(titleLabel, java.awt.BorderLayout.PAGE_START);

        okButton.setText(bundle.getString("LABEL_OK")); // NOI18N

        cancelButton.setText(bundle.getString("LABEL_Cancel")); // NOI18N

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(okButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addContainerGap())
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addGap(28, 28, 28))
        );

        getContentPane().add(buttonsPanel, java.awt.BorderLayout.PAGE_END);

        tabsPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        getContentPane().add(tabsPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JTabbedPane tabsPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    
}
