/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License, Version 1.0 only
 * (the "License").  You may not use this file except in compliance
 * with the License.
 *
 * You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 * or http://www.opensolaris.org/os/licensing.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at usr/src/OPENSOLARIS.LICENSE.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */
/*
 * Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
 * Use is subject to license terms.
 */
package org.opensolaris.webstack.settings.options;

import java.awt.Desktop;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.opensolaris.webstack.settings.model.Environment;
import org.opensolaris.webstack.settings.model.PHPIniModel;

/**
 *
 * @author  ludo
 */
public class PHPPanel extends javax.swing.JPanel implements PropertyChangeListener {

    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/opensolaris/webstack/settings/options/Bundle"); // NOI18N
    PHPIniModel p;

    /** Creates new form PHPPanel */
    public PHPPanel(PHPIniModel phpmodel) {
        p = phpmodel;
        p.addPropertyChangeListener(this);
        initComponents();
        initFromModel();

        
   

    }
    void initFromModel(){
        jCheckBoxdebug.setSelected(p.isDebugMode());
        String error = p.getErrorReporting();
       
        jCheckBoxallErrors.setSelected((error.indexOf("E_ALL")>-1));
        jCheckBoxRunTimeNotices.setSelected((error.indexOf("E_STRICT")>-1));
        jCheckBoxRunTimeWarnings.setSelected((error.indexOf("E_WARNING")>-1));
        jCheckBoxfatalRunTimeErrors.setSelected((error.indexOf("E_ERROR")>-1));        
    }

    void UpdateModel() {

        p.setDebugMode(jCheckBoxdebug.isSelected());
        String error = "";
        if (jCheckBoxallErrors.isSelected()){
            if (error.length()>0){
                error+=" & ";
            }
            error = error+ "E_ALL";
        }
        if (jCheckBoxRunTimeNotices.isSelected()){
            if (error.length()>0){
                error+=" & ";
            }
            error = error+ "E_STRICT";
        }    
        if (jCheckBoxRunTimeWarnings.isSelected()){
            if (error.length()>0){
                error+=" & ";
            }
            error = error+ "E_WARNING";
        }
        if (jCheckBoxfatalRunTimeErrors.isSelected()){
            if (error.length()>0){
                error+=" & ";
            }
            error = error+ "E_ERROR";
        }    
        p.setErrorReporting(error);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonAdvanceConf = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buttonRepair = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jCheckBoxallErrors = new javax.swing.JCheckBox();
        jCheckBoxfatalRunTimeErrors = new javax.swing.JCheckBox();
        jCheckBoxRunTimeWarnings = new javax.swing.JCheckBox();
        jCheckBoxRunTimeNotices = new javax.swing.JCheckBox();
        jCheckBoxdebug = new javax.swing.JCheckBox();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/opensolaris/webstack/settings/options/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("LABEL_Debug")); // NOI18N
        jLabel1.setToolTipText(bundle.getString("LABEL_PHPVERSION")); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText(bundle.getString("LABEL_ERRORREPORTINGLEVEL")); // NOI18N

        buttonAdvanceConf.setText(bundle.getString("LABEL_ADVANCE_CONF")); // NOI18N
        buttonAdvanceConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdvanceConfActionPerformed(evt);
            }
        });

        jLabel3.setText(bundle.getString("LABEL_EDITPHPINI")); // NOI18N
        jLabel3.setEnabled(false);

        buttonRepair.setText(bundle.getString("LABEL_REPAIR")); // NOI18N
        buttonRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRepairActionPerformed(evt);
            }
        });

        jButton1.setText(bundle.getString("LABEL_SHOWPHPINFO")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBoxallErrors.setText(bundle.getString("E_ALL")); // NOI18N

        jCheckBoxfatalRunTimeErrors.setText(bundle.getString("E_ERROR")); // NOI18N

        jCheckBoxRunTimeWarnings.setText(bundle.getString("E_WARNING")); // NOI18N

        jCheckBoxRunTimeNotices.setText(bundle.getString("E_NOTICE")); // NOI18N

        jCheckBoxdebug.setText("enable");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(buttonRepair)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAdvanceConf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                    .addComponent(jCheckBoxallErrors)
                    .addComponent(jCheckBoxdebug)
                    .addComponent(jCheckBoxfatalRunTimeErrors)
                    .addComponent(jCheckBoxRunTimeWarnings)
                    .addComponent(jCheckBoxRunTimeNotices))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxdebug)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxallErrors)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxfatalRunTimeErrors)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxRunTimeWarnings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxRunTimeNotices)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdvanceConf)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRepair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void buttonRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRepairActionPerformed

        Object[] options = {"Yes, repair", "Cancel"};
        int n = JOptionPane.showOptionDialog(null, "question", "Repair", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        if (n==JOptionPane.OK_OPTION){
            
        }
    }//GEN-LAST:event_buttonRepairActionPerformed

    private void buttonAdvanceConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdvanceConfActionPerformed
        Desktop desktop = null;
        // Before more Desktop API is used, first check
        // whether the API is supported by this particular
        // virtual machine (VM) on this particular host.
        if (Desktop.isDesktopSupported()) {
            desktop = Desktop.getDesktop();
        }
        if (desktop.isSupported(Desktop.Action.OPEN)) {
            try {

                desktop.open(new File(Environment.getPhpini()));
            } catch (IOException ex) {
                Logger.getLogger(PHPPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_buttonAdvanceConfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdvanceConf;
    private javax.swing.JButton buttonRepair;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxRunTimeNotices;
    private javax.swing.JCheckBox jCheckBoxRunTimeWarnings;
    private javax.swing.JCheckBox jCheckBoxallErrors;
    private javax.swing.JCheckBox jCheckBoxdebug;
    private javax.swing.JCheckBox jCheckBoxfatalRunTimeErrors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        initFromModel();

    }
}