/*DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

Copyright 1997-2009 Sun Microsystems, Inc. All rights reserved.

The contents of this file are subject to the terms of either the GNU
General Public License Version 2 only ("GPL") or the Common Development
and Distribution License("CDDL") (collectively, the "License").  You
may not use this file except in compliance with the License. You can obtain
a copy of the License at https://glassfish.dev.java.net/public/CDDL+GPL.html
or glassfish/bootstrap/legal/LICENSE.txt.  See the License for the specific
language governing permissions and limitations under the License.

When distributing the software, include this License Header Notice in each
file and include the License file at glassfish/bootstrap/legal/LICENSE.txt.
Sun designates this particular file as subject to the "Classpath" exception
as provided by Sun in the GPL Version 2 section of the License file that
accompanied this code.  If applicable, add the following below the License
Header, with the fields enclosed by brackets [] replaced by your own
identifying information: "Portions Copyrighted [year]
[name of copyright owner]"

Contributor(s):

If you wish your version of this file to be governed by only the CDDL or
only the GPL Version 2, indicate your decision by adding "[Contributor]
elects to include this software in this distribution under the [CDDL or GPL
Version 2] license."  If you don't indicate a single choice of license, a
recipient has the option to distribute your version of this file under
either the CDDL, the GPL Version 2 or to extend the choice of license to
its licensees as provided above.  However, if you add GPL Version 2 code
and therefore, elected the GPL Version 2 license, then the option applies
only if the new code is made subject to such option by the copyright
holder.
 */
package com.sun.enterprise.jst.server.sunappsrv.configurator;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.core.runtime.Platform;

// workaround for eclipse bug 94497
// OpenSolaris doesn't have internal browser or default browser set up properly
public class SolarisBrowserConfigurator {

	private final static String BROWSER_PREFS_PATH = "org.eclipse.core.runtime/.settings"; //$NON-NLS-1$
	private final static String BROWSER_PREFS_FILE = "org.eclipse.ui.browser.prefs"; //$NON-NLS-1$
	private static final String SOLARIS_BROWSER_CONFIG = "#Generated by GlassFish Tools Bundle for Eclipse\n" + //$NON-NLS-1$
		"browsers=<?xml version\\=\"1.0\" encoding\\=\"UTF-8\"?>\\n" + //$NON-NLS-1$
		"<web-browsers current\\=\"0\">\\n" + //$NON-NLS-1$
		"<external location\\=\"/usr/bin/firefox\" name\\=\"Firefox\" parameters\\=\"%URL%\"/>\\n</web-browsers>\n" + //$NON-NLS-1$
		"browser-choice=1\neclipse.preferences.version=1\n"; //$NON-NLS-1$

	public static void configure(IProgressMonitor progressMonitor) throws CoreException {
		String browserPrefsLocation = Platform.getLocation().append(".metadata").append(".plugins").append( //$NON-NLS-1$ //$NON-NLS-2$
				BROWSER_PREFS_PATH).toOSString();

		if ("SunOS".equals(System.getProperty("os.name"))) { //$NON-NLS-1$ //$NON-NLS-2$
			File prefsFile = new File(browserPrefsLocation + File.separatorChar + BROWSER_PREFS_FILE);
        	if (!prefsFile.exists()) {
            	File settingsDirectory = new File(browserPrefsLocation);
        		settingsDirectory.mkdirs();
				try {
					FileWriter writer = new FileWriter(prefsFile);
	        		writer.write(SOLARIS_BROWSER_CONFIG);
	        		writer.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
        	}
        }
	}
}
